# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zoizoi/psyforge/OVAS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zoizoi/psyforge/OVAS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zoizoi/psyforge/OVAS/CMakeFiles /home/zoizoi/psyforge/OVAS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zoizoi/psyforge/OVAS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testOVAS

# Build rule for target.
testOVAS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testOVAS
.PHONY : testOVAS

# fast build rule for target.
testOVAS/fast:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/build
.PHONY : testOVAS/fast

Analyser3D.o: Analyser3D.cpp.o
.PHONY : Analyser3D.o

# target to build an object file
Analyser3D.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Analyser3D.cpp.o
.PHONY : Analyser3D.cpp.o

Analyser3D.i: Analyser3D.cpp.i
.PHONY : Analyser3D.i

# target to preprocess a source file
Analyser3D.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Analyser3D.cpp.i
.PHONY : Analyser3D.cpp.i

Analyser3D.s: Analyser3D.cpp.s
.PHONY : Analyser3D.s

# target to generate assembly for a file
Analyser3D.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Analyser3D.cpp.s
.PHONY : Analyser3D.cpp.s

Analyser4D.o: Analyser4D.cpp.o
.PHONY : Analyser4D.o

# target to build an object file
Analyser4D.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Analyser4D.cpp.o
.PHONY : Analyser4D.cpp.o

Analyser4D.i: Analyser4D.cpp.i
.PHONY : Analyser4D.i

# target to preprocess a source file
Analyser4D.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Analyser4D.cpp.i
.PHONY : Analyser4D.cpp.i

Analyser4D.s: Analyser4D.cpp.s
.PHONY : Analyser4D.s

# target to generate assembly for a file
Analyser4D.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Analyser4D.cpp.s
.PHONY : Analyser4D.cpp.s

CriticalPoint.o: CriticalPoint.cpp.o
.PHONY : CriticalPoint.o

# target to build an object file
CriticalPoint.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/CriticalPoint.cpp.o
.PHONY : CriticalPoint.cpp.o

CriticalPoint.i: CriticalPoint.cpp.i
.PHONY : CriticalPoint.i

# target to preprocess a source file
CriticalPoint.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/CriticalPoint.cpp.i
.PHONY : CriticalPoint.cpp.i

CriticalPoint.s: CriticalPoint.cpp.s
.PHONY : CriticalPoint.s

# target to generate assembly for a file
CriticalPoint.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/CriticalPoint.cpp.s
.PHONY : CriticalPoint.cpp.s

CurvatureFeature.o: CurvatureFeature.cpp.o
.PHONY : CurvatureFeature.o

# target to build an object file
CurvatureFeature.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/CurvatureFeature.cpp.o
.PHONY : CurvatureFeature.cpp.o

CurvatureFeature.i: CurvatureFeature.cpp.i
.PHONY : CurvatureFeature.i

# target to preprocess a source file
CurvatureFeature.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/CurvatureFeature.cpp.i
.PHONY : CurvatureFeature.cpp.i

CurvatureFeature.s: CurvatureFeature.cpp.s
.PHONY : CurvatureFeature.s

# target to generate assembly for a file
CurvatureFeature.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/CurvatureFeature.cpp.s
.PHONY : CurvatureFeature.cpp.s

Data.o: Data.cpp.o
.PHONY : Data.o

# target to build an object file
Data.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Data.cpp.o
.PHONY : Data.cpp.o

Data.i: Data.cpp.i
.PHONY : Data.i

# target to preprocess a source file
Data.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Data.cpp.i
.PHONY : Data.cpp.i

Data.s: Data.cpp.s
.PHONY : Data.s

# target to generate assembly for a file
Data.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Data.cpp.s
.PHONY : Data.cpp.s

Feature.o: Feature.cpp.o
.PHONY : Feature.o

# target to build an object file
Feature.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Feature.cpp.o
.PHONY : Feature.cpp.o

Feature.i: Feature.cpp.i
.PHONY : Feature.i

# target to preprocess a source file
Feature.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Feature.cpp.i
.PHONY : Feature.cpp.i

Feature.s: Feature.cpp.s
.PHONY : Feature.s

# target to generate assembly for a file
Feature.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Feature.cpp.s
.PHONY : Feature.cpp.s

FeatureWeights.o: FeatureWeights.cpp.o
.PHONY : FeatureWeights.o

# target to build an object file
FeatureWeights.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/FeatureWeights.cpp.o
.PHONY : FeatureWeights.cpp.o

FeatureWeights.i: FeatureWeights.cpp.i
.PHONY : FeatureWeights.i

# target to preprocess a source file
FeatureWeights.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/FeatureWeights.cpp.i
.PHONY : FeatureWeights.cpp.i

FeatureWeights.s: FeatureWeights.cpp.s
.PHONY : FeatureWeights.s

# target to generate assembly for a file
FeatureWeights.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/FeatureWeights.cpp.s
.PHONY : FeatureWeights.cpp.s

FlyingSaucersVol4D.o: FlyingSaucersVol4D.cpp.o
.PHONY : FlyingSaucersVol4D.o

# target to build an object file
FlyingSaucersVol4D.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/FlyingSaucersVol4D.cpp.o
.PHONY : FlyingSaucersVol4D.cpp.o

FlyingSaucersVol4D.i: FlyingSaucersVol4D.cpp.i
.PHONY : FlyingSaucersVol4D.i

# target to preprocess a source file
FlyingSaucersVol4D.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/FlyingSaucersVol4D.cpp.i
.PHONY : FlyingSaucersVol4D.cpp.i

FlyingSaucersVol4D.s: FlyingSaucersVol4D.cpp.s
.PHONY : FlyingSaucersVol4D.s

# target to generate assembly for a file
FlyingSaucersVol4D.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/FlyingSaucersVol4D.cpp.s
.PHONY : FlyingSaucersVol4D.cpp.s

FrameBuffer.o: FrameBuffer.cpp.o
.PHONY : FrameBuffer.o

# target to build an object file
FrameBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/FrameBuffer.cpp.o
.PHONY : FrameBuffer.cpp.o

FrameBuffer.i: FrameBuffer.cpp.i
.PHONY : FrameBuffer.i

# target to preprocess a source file
FrameBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/FrameBuffer.cpp.i
.PHONY : FrameBuffer.cpp.i

FrameBuffer.s: FrameBuffer.cpp.s
.PHONY : FrameBuffer.s

# target to generate assembly for a file
FrameBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/FrameBuffer.cpp.s
.PHONY : FrameBuffer.cpp.s

GeoPoint.o: GeoPoint.cpp.o
.PHONY : GeoPoint.o

# target to build an object file
GeoPoint.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoPoint.cpp.o
.PHONY : GeoPoint.cpp.o

GeoPoint.i: GeoPoint.cpp.i
.PHONY : GeoPoint.i

# target to preprocess a source file
GeoPoint.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoPoint.cpp.i
.PHONY : GeoPoint.cpp.i

GeoPoint.s: GeoPoint.cpp.s
.PHONY : GeoPoint.s

# target to generate assembly for a file
GeoPoint.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoPoint.cpp.s
.PHONY : GeoPoint.cpp.s

GeoSequence.o: GeoSequence.cpp.o
.PHONY : GeoSequence.o

# target to build an object file
GeoSequence.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoSequence.cpp.o
.PHONY : GeoSequence.cpp.o

GeoSequence.i: GeoSequence.cpp.i
.PHONY : GeoSequence.i

# target to preprocess a source file
GeoSequence.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoSequence.cpp.i
.PHONY : GeoSequence.cpp.i

GeoSequence.s: GeoSequence.cpp.s
.PHONY : GeoSequence.s

# target to generate assembly for a file
GeoSequence.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoSequence.cpp.s
.PHONY : GeoSequence.cpp.s

GeoSphere.o: GeoSphere.cpp.o
.PHONY : GeoSphere.o

# target to build an object file
GeoSphere.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoSphere.cpp.o
.PHONY : GeoSphere.cpp.o

GeoSphere.i: GeoSphere.cpp.i
.PHONY : GeoSphere.i

# target to preprocess a source file
GeoSphere.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoSphere.cpp.i
.PHONY : GeoSphere.cpp.i

GeoSphere.s: GeoSphere.cpp.s
.PHONY : GeoSphere.s

# target to generate assembly for a file
GeoSphere.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoSphere.cpp.s
.PHONY : GeoSphere.cpp.s

ImplicitVolume4D.o: ImplicitVolume4D.cpp.o
.PHONY : ImplicitVolume4D.o

# target to build an object file
ImplicitVolume4D.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/ImplicitVolume4D.cpp.o
.PHONY : ImplicitVolume4D.cpp.o

ImplicitVolume4D.i: ImplicitVolume4D.cpp.i
.PHONY : ImplicitVolume4D.i

# target to preprocess a source file
ImplicitVolume4D.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/ImplicitVolume4D.cpp.i
.PHONY : ImplicitVolume4D.cpp.i

ImplicitVolume4D.s: ImplicitVolume4D.cpp.s
.PHONY : ImplicitVolume4D.s

# target to generate assembly for a file
ImplicitVolume4D.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/ImplicitVolume4D.cpp.s
.PHONY : ImplicitVolume4D.cpp.s

InfoData.o: InfoData.cpp.o
.PHONY : InfoData.o

# target to build an object file
InfoData.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/InfoData.cpp.o
.PHONY : InfoData.cpp.o

InfoData.i: InfoData.cpp.i
.PHONY : InfoData.i

# target to preprocess a source file
InfoData.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/InfoData.cpp.i
.PHONY : InfoData.cpp.i

InfoData.s: InfoData.cpp.s
.PHONY : InfoData.s

# target to generate assembly for a file
InfoData.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/InfoData.cpp.s
.PHONY : InfoData.cpp.s

InfoSheet.o: InfoSheet.cpp.o
.PHONY : InfoSheet.o

# target to build an object file
InfoSheet.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/InfoSheet.cpp.o
.PHONY : InfoSheet.cpp.o

InfoSheet.i: InfoSheet.cpp.i
.PHONY : InfoSheet.i

# target to preprocess a source file
InfoSheet.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/InfoSheet.cpp.i
.PHONY : InfoSheet.cpp.i

InfoSheet.s: InfoSheet.cpp.s
.PHONY : InfoSheet.s

# target to generate assembly for a file
InfoSheet.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/InfoSheet.cpp.s
.PHONY : InfoSheet.cpp.s

LoadedVol4D.o: LoadedVol4D.cpp.o
.PHONY : LoadedVol4D.o

# target to build an object file
LoadedVol4D.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/LoadedVol4D.cpp.o
.PHONY : LoadedVol4D.cpp.o

LoadedVol4D.i: LoadedVol4D.cpp.i
.PHONY : LoadedVol4D.i

# target to preprocess a source file
LoadedVol4D.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/LoadedVol4D.cpp.i
.PHONY : LoadedVol4D.cpp.i

LoadedVol4D.s: LoadedVol4D.cpp.s
.PHONY : LoadedVol4D.s

# target to generate assembly for a file
LoadedVol4D.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/LoadedVol4D.cpp.s
.PHONY : LoadedVol4D.cpp.s

Mesh.o: Mesh.cpp.o
.PHONY : Mesh.o

# target to build an object file
Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Mesh.cpp.o
.PHONY : Mesh.cpp.o

Mesh.i: Mesh.cpp.i
.PHONY : Mesh.i

# target to preprocess a source file
Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Mesh.cpp.i
.PHONY : Mesh.cpp.i

Mesh.s: Mesh.cpp.s
.PHONY : Mesh.s

# target to generate assembly for a file
Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Mesh.cpp.s
.PHONY : Mesh.cpp.s

MetaballsVol4D.o: MetaballsVol4D.cpp.o
.PHONY : MetaballsVol4D.o

# target to build an object file
MetaballsVol4D.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/MetaballsVol4D.cpp.o
.PHONY : MetaballsVol4D.cpp.o

MetaballsVol4D.i: MetaballsVol4D.cpp.i
.PHONY : MetaballsVol4D.i

# target to preprocess a source file
MetaballsVol4D.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/MetaballsVol4D.cpp.i
.PHONY : MetaballsVol4D.cpp.i

MetaballsVol4D.s: MetaballsVol4D.cpp.s
.PHONY : MetaballsVol4D.s

# target to generate assembly for a file
MetaballsVol4D.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/MetaballsVol4D.cpp.s
.PHONY : MetaballsVol4D.cpp.s

MovingAAElipsoid.o: MovingAAElipsoid.cpp.o
.PHONY : MovingAAElipsoid.o

# target to build an object file
MovingAAElipsoid.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/MovingAAElipsoid.cpp.o
.PHONY : MovingAAElipsoid.cpp.o

MovingAAElipsoid.i: MovingAAElipsoid.cpp.i
.PHONY : MovingAAElipsoid.i

# target to preprocess a source file
MovingAAElipsoid.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/MovingAAElipsoid.cpp.i
.PHONY : MovingAAElipsoid.cpp.i

MovingAAElipsoid.s: MovingAAElipsoid.cpp.s
.PHONY : MovingAAElipsoid.s

# target to generate assembly for a file
MovingAAElipsoid.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/MovingAAElipsoid.cpp.s
.PHONY : MovingAAElipsoid.cpp.s

OVASControl.o: OVASControl.cpp.o
.PHONY : OVASControl.o

# target to build an object file
OVASControl.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/OVASControl.cpp.o
.PHONY : OVASControl.cpp.o

OVASControl.i: OVASControl.cpp.i
.PHONY : OVASControl.i

# target to preprocess a source file
OVASControl.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/OVASControl.cpp.i
.PHONY : OVASControl.cpp.i

OVASControl.s: OVASControl.cpp.s
.PHONY : OVASControl.s

# target to generate assembly for a file
OVASControl.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/OVASControl.cpp.s
.PHONY : OVASControl.cpp.s

PathVisualiser.o: PathVisualiser.cpp.o
.PHONY : PathVisualiser.o

# target to build an object file
PathVisualiser.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/PathVisualiser.cpp.o
.PHONY : PathVisualiser.cpp.o

PathVisualiser.i: PathVisualiser.cpp.i
.PHONY : PathVisualiser.i

# target to preprocess a source file
PathVisualiser.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/PathVisualiser.cpp.i
.PHONY : PathVisualiser.cpp.i

PathVisualiser.s: PathVisualiser.cpp.s
.PHONY : PathVisualiser.s

# target to generate assembly for a file
PathVisualiser.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/PathVisualiser.cpp.s
.PHONY : PathVisualiser.cpp.s

StepToParamConverter.o: StepToParamConverter.cpp.o
.PHONY : StepToParamConverter.o

# target to build an object file
StepToParamConverter.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/StepToParamConverter.cpp.o
.PHONY : StepToParamConverter.cpp.o

StepToParamConverter.i: StepToParamConverter.cpp.i
.PHONY : StepToParamConverter.i

# target to preprocess a source file
StepToParamConverter.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/StepToParamConverter.cpp.i
.PHONY : StepToParamConverter.cpp.i

StepToParamConverter.s: StepToParamConverter.cpp.s
.PHONY : StepToParamConverter.s

# target to generate assembly for a file
StepToParamConverter.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/StepToParamConverter.cpp.s
.PHONY : StepToParamConverter.cpp.s

TemporalChangeFeature.o: TemporalChangeFeature.cpp.o
.PHONY : TemporalChangeFeature.o

# target to build an object file
TemporalChangeFeature.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/TemporalChangeFeature.cpp.o
.PHONY : TemporalChangeFeature.cpp.o

TemporalChangeFeature.i: TemporalChangeFeature.cpp.i
.PHONY : TemporalChangeFeature.i

# target to preprocess a source file
TemporalChangeFeature.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/TemporalChangeFeature.cpp.i
.PHONY : TemporalChangeFeature.cpp.i

TemporalChangeFeature.s: TemporalChangeFeature.cpp.s
.PHONY : TemporalChangeFeature.s

# target to generate assembly for a file
TemporalChangeFeature.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/TemporalChangeFeature.cpp.s
.PHONY : TemporalChangeFeature.cpp.s

TemporalChangeFeature2.o: TemporalChangeFeature2.cpp.o
.PHONY : TemporalChangeFeature2.o

# target to build an object file
TemporalChangeFeature2.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/TemporalChangeFeature2.cpp.o
.PHONY : TemporalChangeFeature2.cpp.o

TemporalChangeFeature2.i: TemporalChangeFeature2.cpp.i
.PHONY : TemporalChangeFeature2.i

# target to preprocess a source file
TemporalChangeFeature2.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/TemporalChangeFeature2.cpp.i
.PHONY : TemporalChangeFeature2.cpp.i

TemporalChangeFeature2.s: TemporalChangeFeature2.cpp.s
.PHONY : TemporalChangeFeature2.s

# target to generate assembly for a file
TemporalChangeFeature2.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/TemporalChangeFeature2.cpp.s
.PHONY : TemporalChangeFeature2.cpp.s

TopologyFeature.o: TopologyFeature.cpp.o
.PHONY : TopologyFeature.o

# target to build an object file
TopologyFeature.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/TopologyFeature.cpp.o
.PHONY : TopologyFeature.cpp.o

TopologyFeature.i: TopologyFeature.cpp.i
.PHONY : TopologyFeature.i

# target to preprocess a source file
TopologyFeature.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/TopologyFeature.cpp.i
.PHONY : TopologyFeature.cpp.i

TopologyFeature.s: TopologyFeature.cpp.s
.PHONY : TopologyFeature.s

# target to generate assembly for a file
TopologyFeature.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/TopologyFeature.cpp.s
.PHONY : TopologyFeature.cpp.s

ViewEvaluator.o: ViewEvaluator.cpp.o
.PHONY : ViewEvaluator.o

# target to build an object file
ViewEvaluator.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/ViewEvaluator.cpp.o
.PHONY : ViewEvaluator.cpp.o

ViewEvaluator.i: ViewEvaluator.cpp.i
.PHONY : ViewEvaluator.i

# target to preprocess a source file
ViewEvaluator.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/ViewEvaluator.cpp.i
.PHONY : ViewEvaluator.cpp.i

ViewEvaluator.s: ViewEvaluator.cpp.s
.PHONY : ViewEvaluator.s

# target to generate assembly for a file
ViewEvaluator.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/ViewEvaluator.cpp.s
.PHONY : ViewEvaluator.cpp.s

ViewPathClusterFinder.o: ViewPathClusterFinder.cpp.o
.PHONY : ViewPathClusterFinder.o

# target to build an object file
ViewPathClusterFinder.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/ViewPathClusterFinder.cpp.o
.PHONY : ViewPathClusterFinder.cpp.o

ViewPathClusterFinder.i: ViewPathClusterFinder.cpp.i
.PHONY : ViewPathClusterFinder.i

# target to preprocess a source file
ViewPathClusterFinder.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/ViewPathClusterFinder.cpp.i
.PHONY : ViewPathClusterFinder.cpp.i

ViewPathClusterFinder.s: ViewPathClusterFinder.cpp.s
.PHONY : ViewPathClusterFinder.s

# target to generate assembly for a file
ViewPathClusterFinder.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/ViewPathClusterFinder.cpp.s
.PHONY : ViewPathClusterFinder.cpp.s

Volume4D.o: Volume4D.cpp.o
.PHONY : Volume4D.o

# target to build an object file
Volume4D.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Volume4D.cpp.o
.PHONY : Volume4D.cpp.o

Volume4D.i: Volume4D.cpp.i
.PHONY : Volume4D.i

# target to preprocess a source file
Volume4D.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Volume4D.cpp.i
.PHONY : Volume4D.cpp.i

Volume4D.s: Volume4D.cpp.s
.PHONY : Volume4D.s

# target to generate assembly for a file
Volume4D.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Volume4D.cpp.s
.PHONY : Volume4D.cpp.s

testOVAS.o: testOVAS.cpp.o
.PHONY : testOVAS.o

# target to build an object file
testOVAS.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/testOVAS.cpp.o
.PHONY : testOVAS.cpp.o

testOVAS.i: testOVAS.cpp.i
.PHONY : testOVAS.i

# target to preprocess a source file
testOVAS.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/testOVAS.cpp.i
.PHONY : testOVAS.cpp.i

testOVAS.s: testOVAS.cpp.s
.PHONY : testOVAS.s

# target to generate assembly for a file
testOVAS.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/testOVAS.cpp.s
.PHONY : testOVAS.cpp.s

testVol4D.o: testVol4D.cpp.o
.PHONY : testVol4D.o

# target to build an object file
testVol4D.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/testVol4D.cpp.o
.PHONY : testVol4D.cpp.o

testVol4D.i: testVol4D.cpp.i
.PHONY : testVol4D.i

# target to preprocess a source file
testVol4D.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/testVol4D.cpp.i
.PHONY : testVol4D.cpp.i

testVol4D.s: testVol4D.cpp.s
.PHONY : testVol4D.s

# target to generate assembly for a file
testVol4D.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/testVol4D.cpp.s
.PHONY : testVol4D.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... testOVAS"
	@echo "... Analyser3D.o"
	@echo "... Analyser3D.i"
	@echo "... Analyser3D.s"
	@echo "... Analyser4D.o"
	@echo "... Analyser4D.i"
	@echo "... Analyser4D.s"
	@echo "... CriticalPoint.o"
	@echo "... CriticalPoint.i"
	@echo "... CriticalPoint.s"
	@echo "... CurvatureFeature.o"
	@echo "... CurvatureFeature.i"
	@echo "... CurvatureFeature.s"
	@echo "... Data.o"
	@echo "... Data.i"
	@echo "... Data.s"
	@echo "... Feature.o"
	@echo "... Feature.i"
	@echo "... Feature.s"
	@echo "... FeatureWeights.o"
	@echo "... FeatureWeights.i"
	@echo "... FeatureWeights.s"
	@echo "... FlyingSaucersVol4D.o"
	@echo "... FlyingSaucersVol4D.i"
	@echo "... FlyingSaucersVol4D.s"
	@echo "... FrameBuffer.o"
	@echo "... FrameBuffer.i"
	@echo "... FrameBuffer.s"
	@echo "... GeoPoint.o"
	@echo "... GeoPoint.i"
	@echo "... GeoPoint.s"
	@echo "... GeoSequence.o"
	@echo "... GeoSequence.i"
	@echo "... GeoSequence.s"
	@echo "... GeoSphere.o"
	@echo "... GeoSphere.i"
	@echo "... GeoSphere.s"
	@echo "... ImplicitVolume4D.o"
	@echo "... ImplicitVolume4D.i"
	@echo "... ImplicitVolume4D.s"
	@echo "... InfoData.o"
	@echo "... InfoData.i"
	@echo "... InfoData.s"
	@echo "... InfoSheet.o"
	@echo "... InfoSheet.i"
	@echo "... InfoSheet.s"
	@echo "... LoadedVol4D.o"
	@echo "... LoadedVol4D.i"
	@echo "... LoadedVol4D.s"
	@echo "... Mesh.o"
	@echo "... Mesh.i"
	@echo "... Mesh.s"
	@echo "... MetaballsVol4D.o"
	@echo "... MetaballsVol4D.i"
	@echo "... MetaballsVol4D.s"
	@echo "... MovingAAElipsoid.o"
	@echo "... MovingAAElipsoid.i"
	@echo "... MovingAAElipsoid.s"
	@echo "... OVASControl.o"
	@echo "... OVASControl.i"
	@echo "... OVASControl.s"
	@echo "... PathVisualiser.o"
	@echo "... PathVisualiser.i"
	@echo "... PathVisualiser.s"
	@echo "... StepToParamConverter.o"
	@echo "... StepToParamConverter.i"
	@echo "... StepToParamConverter.s"
	@echo "... TemporalChangeFeature.o"
	@echo "... TemporalChangeFeature.i"
	@echo "... TemporalChangeFeature.s"
	@echo "... TemporalChangeFeature2.o"
	@echo "... TemporalChangeFeature2.i"
	@echo "... TemporalChangeFeature2.s"
	@echo "... TopologyFeature.o"
	@echo "... TopologyFeature.i"
	@echo "... TopologyFeature.s"
	@echo "... ViewEvaluator.o"
	@echo "... ViewEvaluator.i"
	@echo "... ViewEvaluator.s"
	@echo "... ViewPathClusterFinder.o"
	@echo "... ViewPathClusterFinder.i"
	@echo "... ViewPathClusterFinder.s"
	@echo "... Volume4D.o"
	@echo "... Volume4D.i"
	@echo "... Volume4D.s"
	@echo "... testOVAS.o"
	@echo "... testOVAS.i"
	@echo "... testOVAS.s"
	@echo "... testVol4D.o"
	@echo "... testVol4D.i"
	@echo "... testVol4D.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

