# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zoizoi/psyforge/OVAS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zoizoi/psyforge/OVAS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zoizoi/psyforge/OVAS/CMakeFiles /home/zoizoi/psyforge/OVAS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zoizoi/psyforge/OVAS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testOVAS

# Build rule for target.
testOVAS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testOVAS
.PHONY : testOVAS

# fast build rule for target.
testOVAS/fast:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/build
.PHONY : testOVAS/fast

Analyser3D.o: Analyser3D.cpp.o
.PHONY : Analyser3D.o

# target to build an object file
Analyser3D.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Analyser3D.cpp.o
.PHONY : Analyser3D.cpp.o

Analyser3D.i: Analyser3D.cpp.i
.PHONY : Analyser3D.i

# target to preprocess a source file
Analyser3D.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Analyser3D.cpp.i
.PHONY : Analyser3D.cpp.i

Analyser3D.s: Analyser3D.cpp.s
.PHONY : Analyser3D.s

# target to generate assembly for a file
Analyser3D.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Analyser3D.cpp.s
.PHONY : Analyser3D.cpp.s

Analyser4D.o: Analyser4D.cpp.o
.PHONY : Analyser4D.o

# target to build an object file
Analyser4D.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Analyser4D.cpp.o
.PHONY : Analyser4D.cpp.o

Analyser4D.i: Analyser4D.cpp.i
.PHONY : Analyser4D.i

# target to preprocess a source file
Analyser4D.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Analyser4D.cpp.i
.PHONY : Analyser4D.cpp.i

Analyser4D.s: Analyser4D.cpp.s
.PHONY : Analyser4D.s

# target to generate assembly for a file
Analyser4D.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Analyser4D.cpp.s
.PHONY : Analyser4D.cpp.s

Feature.o: Feature.cpp.o
.PHONY : Feature.o

# target to build an object file
Feature.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Feature.cpp.o
.PHONY : Feature.cpp.o

Feature.i: Feature.cpp.i
.PHONY : Feature.i

# target to preprocess a source file
Feature.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Feature.cpp.i
.PHONY : Feature.cpp.i

Feature.s: Feature.cpp.s
.PHONY : Feature.s

# target to generate assembly for a file
Feature.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Feature.cpp.s
.PHONY : Feature.cpp.s

GeoPoint.o: GeoPoint.cpp.o
.PHONY : GeoPoint.o

# target to build an object file
GeoPoint.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoPoint.cpp.o
.PHONY : GeoPoint.cpp.o

GeoPoint.i: GeoPoint.cpp.i
.PHONY : GeoPoint.i

# target to preprocess a source file
GeoPoint.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoPoint.cpp.i
.PHONY : GeoPoint.cpp.i

GeoPoint.s: GeoPoint.cpp.s
.PHONY : GeoPoint.s

# target to generate assembly for a file
GeoPoint.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoPoint.cpp.s
.PHONY : GeoPoint.cpp.s

GeoSequence.o: GeoSequence.cpp.o
.PHONY : GeoSequence.o

# target to build an object file
GeoSequence.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoSequence.cpp.o
.PHONY : GeoSequence.cpp.o

GeoSequence.i: GeoSequence.cpp.i
.PHONY : GeoSequence.i

# target to preprocess a source file
GeoSequence.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoSequence.cpp.i
.PHONY : GeoSequence.cpp.i

GeoSequence.s: GeoSequence.cpp.s
.PHONY : GeoSequence.s

# target to generate assembly for a file
GeoSequence.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoSequence.cpp.s
.PHONY : GeoSequence.cpp.s

GeoSphere.o: GeoSphere.cpp.o
.PHONY : GeoSphere.o

# target to build an object file
GeoSphere.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoSphere.cpp.o
.PHONY : GeoSphere.cpp.o

GeoSphere.i: GeoSphere.cpp.i
.PHONY : GeoSphere.i

# target to preprocess a source file
GeoSphere.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoSphere.cpp.i
.PHONY : GeoSphere.cpp.i

GeoSphere.s: GeoSphere.cpp.s
.PHONY : GeoSphere.s

# target to generate assembly for a file
GeoSphere.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/GeoSphere.cpp.s
.PHONY : GeoSphere.cpp.s

ImplicitVolume4D.o: ImplicitVolume4D.cpp.o
.PHONY : ImplicitVolume4D.o

# target to build an object file
ImplicitVolume4D.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/ImplicitVolume4D.cpp.o
.PHONY : ImplicitVolume4D.cpp.o

ImplicitVolume4D.i: ImplicitVolume4D.cpp.i
.PHONY : ImplicitVolume4D.i

# target to preprocess a source file
ImplicitVolume4D.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/ImplicitVolume4D.cpp.i
.PHONY : ImplicitVolume4D.cpp.i

ImplicitVolume4D.s: ImplicitVolume4D.cpp.s
.PHONY : ImplicitVolume4D.s

# target to generate assembly for a file
ImplicitVolume4D.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/ImplicitVolume4D.cpp.s
.PHONY : ImplicitVolume4D.cpp.s

StepToParamConverter.o: StepToParamConverter.cpp.o
.PHONY : StepToParamConverter.o

# target to build an object file
StepToParamConverter.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/StepToParamConverter.cpp.o
.PHONY : StepToParamConverter.cpp.o

StepToParamConverter.i: StepToParamConverter.cpp.i
.PHONY : StepToParamConverter.i

# target to preprocess a source file
StepToParamConverter.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/StepToParamConverter.cpp.i
.PHONY : StepToParamConverter.cpp.i

StepToParamConverter.s: StepToParamConverter.cpp.s
.PHONY : StepToParamConverter.s

# target to generate assembly for a file
StepToParamConverter.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/StepToParamConverter.cpp.s
.PHONY : StepToParamConverter.cpp.s

Volume4D.o: Volume4D.cpp.o
.PHONY : Volume4D.o

# target to build an object file
Volume4D.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Volume4D.cpp.o
.PHONY : Volume4D.cpp.o

Volume4D.i: Volume4D.cpp.i
.PHONY : Volume4D.i

# target to preprocess a source file
Volume4D.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Volume4D.cpp.i
.PHONY : Volume4D.cpp.i

Volume4D.s: Volume4D.cpp.s
.PHONY : Volume4D.s

# target to generate assembly for a file
Volume4D.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/Volume4D.cpp.s
.PHONY : Volume4D.cpp.s

abstractFeature.o: abstractFeature.cpp.o
.PHONY : abstractFeature.o

# target to build an object file
abstractFeature.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/abstractFeature.cpp.o
.PHONY : abstractFeature.cpp.o

abstractFeature.i: abstractFeature.cpp.i
.PHONY : abstractFeature.i

# target to preprocess a source file
abstractFeature.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/abstractFeature.cpp.i
.PHONY : abstractFeature.cpp.i

abstractFeature.s: abstractFeature.cpp.s
.PHONY : abstractFeature.s

# target to generate assembly for a file
abstractFeature.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/abstractFeature.cpp.s
.PHONY : abstractFeature.cpp.s

testOVAS.o: testOVAS.cpp.o
.PHONY : testOVAS.o

# target to build an object file
testOVAS.cpp.o:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/testOVAS.cpp.o
.PHONY : testOVAS.cpp.o

testOVAS.i: testOVAS.cpp.i
.PHONY : testOVAS.i

# target to preprocess a source file
testOVAS.cpp.i:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/testOVAS.cpp.i
.PHONY : testOVAS.cpp.i

testOVAS.s: testOVAS.cpp.s
.PHONY : testOVAS.s

# target to generate assembly for a file
testOVAS.cpp.s:
	$(MAKE) -f CMakeFiles/testOVAS.dir/build.make CMakeFiles/testOVAS.dir/testOVAS.cpp.s
.PHONY : testOVAS.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... testOVAS"
	@echo "... Analyser3D.o"
	@echo "... Analyser3D.i"
	@echo "... Analyser3D.s"
	@echo "... Analyser4D.o"
	@echo "... Analyser4D.i"
	@echo "... Analyser4D.s"
	@echo "... Feature.o"
	@echo "... Feature.i"
	@echo "... Feature.s"
	@echo "... GeoPoint.o"
	@echo "... GeoPoint.i"
	@echo "... GeoPoint.s"
	@echo "... GeoSequence.o"
	@echo "... GeoSequence.i"
	@echo "... GeoSequence.s"
	@echo "... GeoSphere.o"
	@echo "... GeoSphere.i"
	@echo "... GeoSphere.s"
	@echo "... ImplicitVolume4D.o"
	@echo "... ImplicitVolume4D.i"
	@echo "... ImplicitVolume4D.s"
	@echo "... StepToParamConverter.o"
	@echo "... StepToParamConverter.i"
	@echo "... StepToParamConverter.s"
	@echo "... Volume4D.o"
	@echo "... Volume4D.i"
	@echo "... Volume4D.s"
	@echo "... abstractFeature.o"
	@echo "... abstractFeature.i"
	@echo "... abstractFeature.s"
	@echo "... testOVAS.o"
	@echo "... testOVAS.i"
	@echo "... testOVAS.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

